### ISSUE TITLE
AIOT Botania

### ISSUE THREAD

**Issue by derNiklaas** [EmosewaPixel/The-Pixel-Community-Pack#12]
If Botania is in the Pack there should be AIOT  (All in one tool) Botania by MelanX and derkalaender 

Link to AIOT Botania: https://minecraft.curseforge.com/projects/aiot-botania

**Comment by EmosewaPixel** [comment]
Only if Tinker's ends up not being in the pack (cuz so many mods add Tinker's support to Botania)

**Comment by EmosewaPixel** [comment]
Well, that ended up being true.
