### ISSUE TITLE
World modification mods

### ISSUE THREAD

**Issue by milkev** [EmosewaPixel/The-Pixel-Community-Pack#25]
These affect the vanilla biomes/dimensions. Unsure if they will support its from other mods.
https://minecraft.curseforge.com/projects/end-reborn - End Reborn. Adds some cool content to the end, as well as some more story to the vanilla minecraft story. Depending on how this packs questline/story turns out this may or may not be a good addition.
https://minecraft.curseforge.com/projects/recurrent-complex - Recurrent Complex. Adds more buildings to the world. These can be custom made for the modpack, and could be part of the questline/story. again, depends on how the modpack story turns out.
https://minecraft.curseforge.com/projects/biome-paint-tools - Biome Paint Tools. Ever get annoyed that you are expanding your base and suddenly the blocks are a different colour than you want? biome painter would be a excellent (albeit slow) solution to this problem. This is the only mod for 1.12 that can change biomes via survival mode that i found.
https://minecraft.curseforge.com/projects/wild-crops - Wild Crops. You can set crops to randomly grow in the world. Unsure if it works with other mods. Could be a cool addition requiring the player to get certain resources by finding a certain crop.

**Comment by EmosewaPixel** [comment]
I think in this pack i'm going to have it so the overworld has no generated structures. (wild crops is a no cuz we're going to have AgriCraft)
