### ISSUE TITLE
No Tinkers Construct

### ISSUE THREAD

**Issue by car-keys** [EmosewaPixel/The-Pixel-Community-Pack#4]
Tinkers invalidates all other early-mid game mod tools, and provides a easily automatable earlygame source of ore doubling and smelting. Almost every modded player has done Tinkers to death and it is just a big grind at this point. If we want a "tool mod" I'm sure there's plenty of lesser known mods we can consider.

**Comment by bugreporter0** [comment]
+1

**Comment by ChristophGra** [comment]
Maybe gating it could work for you?

**Comment by EmosewaPixel** [comment]
Yeah, I always gate the smeltery to mid-game in my expert packs, so the ore doubling isn't a fair statement. Generally my plan was to use https://minecraft.curseforge.com/projects/tinkered-hegemony?gameCategorySlug=mc-mods&projectID=292491 so only Tinker's tools are available and get rid of some materials Iguana Tweaks-style. The thing with Tinker's is that it provides more tool modularity than any other mod. I was also planning on using Tinker's Armory... I'll think about it.

**Comment by bigyihsuan** [comment]
If we're foregoing TiC, then perhaps [Silent's Gems](https://minecraft.curseforge.com/projects/silents-gems?gameCategorySlug=mc-mods&projectID=220311) and [Silent's Gems: Extra Parts](https://minecraft.curseforge.com/projects/silents-gems-extra-parts?gameCategorySlug=mc-mods&projectID=245281)? I don't see this mod too often, and it provide a good alternative to TiC.

**Comment by EmosewaPixel** [comment]
I disagree, I've seen it in several packs. Still, it's just not as configurable as Tinker's. I can't have a cavemany start with Silent's Gems. You see, in that case that the pack ends up being an overworld pack, I was also thinking about using this mod: https://minecraft.curseforge.com/projects/tinkersurvival?gameCategorySlug=mc-mods&projectID=294667 It seems interesting and I've never seen it used.

**Comment by EmosewaPixel** [comment]
We'll settle this formally https://www.strawpoll.me/16883341

**Comment by bigyihsuan** [comment]
The main question is, how much TiC will you want us to use? Will you tweak the config so that you only need Tinkers, add in Tinker Tool Leveling and PlusTiC and go crazy with TiC tools and armor, or just have it be vanilla TiC and encourage the use of other mods' tools?

**Comment by EmosewaPixel** [comment]
Tinker's Leveling, Construct's Armory, Armory Expansion, PlusTIC, Tinker's JEI, Moar Tinkers, Tinker's egemony, Tinker's Survival (Tinker I/O , Tinker's Complement and Yoyos would have to be voted on)

**Comment by KingIonTrueLove** [comment]
Strawpoll is kinda biased if its only linked in the 'no tinkers' suggestion page :P 
I love tinkers myself, and really need to try tinker's armory sometime.

**Comment by tyler489** [comment]
i would be fine with either... IF silent gems is in the pack..

**Comment by EmosewaPixel** [comment]
I guess Tinkers' is staying
