### ISSUE TITLE
Mod Ideas

### ISSUE THREAD

**Issue by yznpku** [EmosewaPixel/The-Pixel-Community-Pack#6]
- Gregtech

- Botania

- Avaritia

I suggest making early game as short as possible (tinker's construct is a good start) and explore more into end game possibilities.

**Comment by Valdevon** [comment]
I love GregTech, but its a very isolating mod and doesn't have place in a community pack IMO. A pack that uses gregtech should be built around gregtech, and most people don't enjoy the playstyle.

Also, GregTech and "making early game as short as possible" don't mix well together

**Comment by EmosewaPixel** [comment]
Yeah, I agree. I've already spent 5 months of my life working on/with GregTech. I would not put it in a pack like this. Also, Avaritia's already been suggested and Botania has kinda been suggested, so I'm closing this.
